# Yaml File i.e Github Workflow File to Migrate the Repos

name: Migrate Repository

on:
  push:
    branches:
      - main  # Replace with the branch name

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2

      - name: Set Up Git
        run: |
          git config --global user.email "your_email_id@xyz.com"
          git config --global user.name "Your_Github_Username"

      - name: Clone Destination Repository
        run: git clone https://github.com/destination-account/destination-repo.git  # Replace the following URL with the destination repository URL
        env:
          DESTINATION_TOKEN: ${{ secrets.DESTINATION_TOKEN }}  # DESTINATION_TOKEN-Github Token of the destination account

      - name: Copy Files
        run: |
          cp -r ./* destination-repo/
          cd destination-repo
          git add .
          git commit -m "Migrate files"
          git push origin main
        env:
          DESTINATION_TOKEN: ${{ secrets.DESTINATION_TOKEN }}

      # Migrate Secrets
      - name: Migrate Secrets
        run: |
          echo "Migrating secrets..."
          echo "${{ secrets.SOURCE_SECRET }}" >> your-destination-repo/.env  # Migrating secret to a .env file
        env:
          SOURCE_SECRET: ${{ secrets.SOURCE_SECRET }}    #  SOURCE_SECRET-Name of all the Secrets of the source repository
